pool:
  vmImage: 'macOS-10.14'

# don't trigger on tag creation
# see https://docs.microsoft.com/ja-jp/azure/devops/pipelines/repos/github?view=vsts#trigger-builds-for-github-tags
trigger:
  branches:
    include:
      - master
    exclude:
      - refs/tags/*

steps:
- script: |
    git clone https://github.com/SebastianSzturo/Dictionary-Development-Kit.git "$HOME"/'Dictionary Development Kit'
  displayName: 'Clone DDK'
- script: |
    ./rsync.sh
  displayName: 'Rsync JMdict_e'
- script: |
    ./build-saxon.sh
  displayName: 'Transform XML to Apple dictionary XML'
- script: |
    make
  displayName: 'Build dictionary'
- script: |
    hdiutil create tmp.dmg -ov -volname "JMdict" -fs HFS+ -srcfolder "./objects/JMDict.dictionary"
    hdiutil convert tmp.dmg -format UDZO -o JMdict.dmg
  displayName: 'Package dictionary'
- script: |
    make clean
    rm tmp.dmg
  displayName: 'Cleanup'

- task: CopyFiles@2
  inputs:
    contents: '**/*.dmg'
    targetFolder: '$(build.artifactStagingDirectory)'

- task: GithubRelease@0
  inputs:
    gitHubConnection: makigumo
    repositoryName: 'makigumo/jmdict-mac-dic'
    action: 'Create' # Options: create, edit, discard
    target: '$(build.sourceVersion)' # Required when action == create || action == edit
    tagSource: 'manual' # Required when action == create. Options: auto, manual
    tag: '$(Build.BuildNumber)' # Required when action == edit || action == discard || tagSource == manual
    #title: # Optional
    #releaseNotesSource: 'file' # Optional. Options: file, input
    #releaseNotesFile: # Optional
    #releaseNotes: # Optional
    assets: '$(build.artifactStagingDirectory)/*.dmg'
    #assetUploadMode: 'delete' # Optional. Options: delete, replace
    #isDraft: false # Optional
    #isPreRelease: false # Optional
    #addChangeLog: true # Optional