name: CI

on:
  schedule:
    - cron: "0 5 * * 6"
  workflow_dispatch:

jobs:
  build:

    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Clone DDK
        run: |
          git clone https://github.com/SebastianSzturo/Dictionary-Development-Kit.git "$HOME"/'Dictionary Development Kit'
      - name: Rsync JMdict_e
        run: |
          ./rsync.sh
      - name: Transform XML to Apple dictionary XML
        run: |
          ./build-saxon.sh
      - name: Prepare plist file
        run: |
          cat JMDict.plist.in | m4 -DYEAR=$(date +%Y) -DVERSION_DATE=$(date +%Y.%m.%d) > JMDict.plist
      - name: Build dictionary
        run: |
          make
      - name: Package dictionary
        run: |
          mkdir pkgdir
          cp -R objects/*.dictionary pkgdir
          hdiutil create tmp.dmg -ov -volname "JMdict" -fs HFS+ -srcfolder "./pkgdir"
          hdiutil convert tmp.dmg -format UDZO -o JMdict.dmg
      - name: Cleanup
        run: |
          make clean
          rm -rf pkgdir
          rm tmp.dmg
      - name: Get current date
        id: date
        run: |
          echo "build-date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.date.outputs.build-date }}.${{ github.run_id }}
          artifacts: "JMDict.dmg"
          artifactContentType: application/x-apple-diskimage
          body: "Release of wadoku.de data ${{ steps.date.outputs.release-date }}.\nBuilt on ${{ steps.date.outputs.build-date }}."
          token: ${{ secrets.GITHUB_TOKEN }}
